name: Test functions over pull requests

on:
  pull_request:
    types: [opened]
    branches-ignore:
      - testing
  push:
    branches:
      - 'testing'    

jobs:
  build_stategy_matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        # This is very hacky, but it goes like that:
        # 1) Associate base_ref with origin/base_ref since actions/checkout doesn't do it, if we don't do that we won't be able to check the actual diff
        # 2) Build JSON string
        #  2.1) Add beginning of JSON
        #  2.2) Get diff between origin/base_ref and the checked-out repo => git diff ${{ github.base_ref }} --name-only
        #  2.3) Clean the file name and leave us only with directories => sed 's,/*[^/]\+/*$,,'
        #  2.4) Sort and keep only unique directories => sort | uniq
        #  2.5) Remove directories starting with '.' => grep -v '^\.'
        #  2.6) Add quotation marks to all strings => sed 's/.*/"&"/'
        #  2.7) Add comma suffix to all strings excluding the last one => sed '$!s/.*/&,/'
        #  2.8) Close JSON
        # 3) Save matrix JSON to output
        # This is previous fetch command that stopped working (wile invetsigating added WA bello in run sectiong): git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
        # This is old git diff version:             git diff ${{ github.base_ref }} --name-only | sed 's,/*[^/]\+/*$,,' | sort | uniq | grep -v '^\.' | sed 's/.*/"&"/' | sed '$!s/.*/&,/'
        # Based on instructions regarding https://docs.github.com/en/actions/learn-github-actions/contexts#github-context , github.base_ref triggers a workflow run is either pull_request or pull_request_target
        run: |
          git fetch --no-tags --prune --depth=1 origin ${{ github.base_ref }}:${{ github.base_ref }}
          matrix=$((
            echo '{ "package" : ['
            git diff ${{ github.base_ref }} --name-only | sed 's,/*[^/]\+/*$,,' | sort | uniq | grep -v '^\.' | sed 's/.*/"&"/' | sed '$!s/.*/&,/'
            echo " ]}"
          ) | jq 'del(.[][] | select(. == ""))'  -c)
          echo "::set-output name=matrix::$matrix"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  check_matrix:
    runs-on: ubuntu-latest
    needs: build_stategy_matrix
    steps:
      - name: Install json2yaml
        run: |
          sudo npm install -g json2yaml
      - name: Check matrix definition
        run: |
          matrix='${{ needs.build_stategy_matrix.outputs.matrix }}'
          echo $matrix
          echo $matrix | jq .
          echo $matrix | json2yaml
  run_monorepo_tests:
    needs: build_stategy_matrix
    runs-on: ubuntu-latest
    strategy:
      # matrix: [{"package": some package that changed}, {...}, ...]
      matrix: ${{fromJson(needs.build_stategy_matrix.outputs.matrix)}}
    steps:
      # Source
      - name: Checkout current repo
        uses: actions/checkout@v2
        with:
          path: functions
      # Install python
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      # Install dependencies
      - uses: actions/cache@v1
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('functions/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install -r functions/requirements.txt
#      - name: Run item validation
        # add functionality for test single item
#        run: python functions/functions.py  run-tests -r functions -s items
      - name: Run py tests
        run: python functions/functions.py  run-tests -r functions -s py -fn ${{ matrix.package }}
#      - name: Run ipynb tests
#        run: python functions/functions.py  run-tests -r functions -s ipynb
      - name: Clean
        run: |
          rm -rf functions
#    tests:
#    name: Run tests
#    runs-on: self-hosted
#    steps:
#      # Source
#      - name: Checkout current repo
#        uses: actions/checkout@v2
#        with:
#          path: functions
#      # Install python
#      - name: Install python
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.7
#      # Install dependencies
#      - uses: actions/cache@v1
#        id: cache
#        with:
#          path: ~/.cache/pip
#          key: ${{ runner.os }}-pip-${{ hashFiles('functions/requirements.txt') }}
#          restore-keys: |
#            ${{ runner.os }}-pip-
#      - name: Install requirements
#        run: |
#          pip install --upgrade pip
#          pip install -r functions/requirements.txt
#      - name: Run item validation
#        run: python functions/functions.py  run-tests -r functions -s items
#      - name: Run py tests
#        run: python functions/functions.py  run-tests -r functions -s py -mp True
##      - name: Run ipynb tests
##        run: python functions/functions.py  run-tests -r functions -s ipynb
#      - name: Clean
#        run: |
#          rm -rf functions
